## 实验二 

<font color=Tomato>**NumPy**</font>是用于科学计算的一个开源的Python程序库，代表 “Numeric Python”。
它为Python提供了高性能数组与矩阵运算处理能力，为数据分析提供了数据处理的基础功能。


<font color=Tomato>**第一部分**</font>-Numpy科学计算  

请在下面<font color=Tomato>**每一行注释**</font>下添加对应的代码

In [2]:
#导入numpy库，并取一个别名np
import numpy as np

<font color=Tomato>1. 普通数组创建</font>  

函数array可以将Python的列表、元组、数组或其他序列类型作为参数创建ndarray数组。

格式为 *数组名 = np.array(x)*，x为其他序列类型。


In [2]:
#1.1 生成一维列表作为array参数
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
#1.2 打印输出，type函数查看类型
print(a1)
type(a1)
#1.3 生成二维列表作为array参数
a2 = np.array([[1,3,5],[2,4,6]])
print(a2)
#1.4 生成元组作为array参数
a3 = np.array((1, 2, 3))
print(a3)
#1.5 生成字典作为array参数
a4 = np.array({'yang':12, 'ss':45})
print(a4)
#1.6 生成字符串作为array参数
a5 = np.array('abcdef')
print(a5)

[1 2 3 4 5]
[[1 3 5]
 [2 4 6]]
[1 2 3]
{'yang': 12, 'ss': 45}
abcdef


<font color=Tomato>2. 特殊数组创建  </font>    

*np.empty((x1,x2))* 创建一个指定维度、数据类型的未初始化的数组；  

*np.zeros((x1,x2))* 创建x1行x2列的numpy数组，元素均为0；  

*np.ones((x1,x2))* 创建x1行x2列的numpy数组，元素均为1；  
    
*np.eye(x1)* 创建x1行x1列的numpy数组，对角线元素均为1，其余为0。

In [3]:
#2.1 创建2行3列的numpy数组，元素均为0
b=np.empty((2,3))
print(b)

#2.2 创建3行5列的numpy数组，元素均为0
b1=np.zeros((3,5))
print(b1)

#2.3 创建4行2列的numpy数组，元素均为1
b2=np.ones((4,2))
print(b2)

#2.4 创建3行3列的numpy数组，对角线元素均为1，其余为0
b3=np.eye(3)
print(b3)


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<font color=Tomato>3. 随机数组创建  </font>  

*np.random.rand(x1, x2)*, 产生[0, 1)范围的浮点随机数  

*np.random.randint(x1, x2,size=(x3, x4))*, 产生x1至x2范围的随机整数，生成x3行x4列。 

In [4]:
#3.1 生成1行2列数组，值服从[0, 1)之间的均匀分布。
c=np.random.rand(1,2)
print(c)
#3.2 生成3行4列数组，值范围在0到9之间。
import numpy as np
np.random.seed(1)
a = np.random.randint(0,9,size=(3,4))
print(a)

[[0.40897046 0.61433076]]
[[5 8 5 0]
 [0 1 7 6]
 [2 4 5 2]]


<font color=Tomato>4. 数值范围创建 </font>     

*np.arange([start, ]stop, [step, ]dtype=None)* 
    
start:起点值；可忽略不写，默认从0开始；stop:终点值；生成的元素不包括结束值；step:步长；可忽略不写，默认步长为1；dtype:默认为None，设置显示元素的数据类型。 
    
 *np.linspace(start,end,num)*  
 
 通过定义均匀间隔创建数值序列。其实，需要指定间隔起始点、终止端，以及指定分隔值总数（包括起始点和终止点）；最终函数返回间隔类均匀分布的数值序列。


In [5]:
#4.1 生成终点值为7，起点值为3，步长为0.5(小数)的数组。
import numpy as np
d=np.arange(3,7,0.5,dtype=None)
print(d)
#4.2 生成起点值为5，终点值为100，分隔值为10的数组。
d1=np.linspace(5,100,10)
print(d1)

[3.  3.5 4.  4.5 5.  5.5 6.  6.5]
[  5.          15.55555556  26.11111111  36.66666667  47.22222222
  57.77777778  68.33333333  78.88888889  89.44444444 100.        ]


<font color=Tomato>5. 列表转数组，数组转列表</font>  

列表转数组 *np.asarray(list)*  

数组转列表 *np.ndarray.tolist(array)*

In [6]:
#5.1 将[1,2,3,4,5]转换为numpy数组
e=np.asarray([1,2,3,4,5])
print(e)
#5.2 将numpy数组转换回列表[1,2,3,4,5]
e1=np.array([1,2,3,4,5])
e2=e1.tolist()
print(e2)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


<font color=Tomato>6. 数组对象属性</font>  


In [7]:
import numpy as np
#根据下面数组完成练习
P6 = np.array([[1,2,3],[4,5,6]]) 
#6.1 np.ndim 数据轴个数
f=np.ndim(P6)
print(f)
#6.2 np.shape 维度
f1=np.shape(P6)
print(f1)
#6.3 np.size 元素总个数
f2=np.size(P6)
print(f2)
#6.4 np.dtype 数据类型
f3=P6.dtype
print(f3)
#6.5 np.T 数组的行列转置
f4=P6.T
print(f4)
#6.6 使用astype()把数组元素转换为浮点型，用dtype查看明确数据类型。
f5=P6.astype(float)
print(f5)
f5.dtype


2
(2, 3)
6
int32
[[1 4]
 [2 5]
 [3 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float64')

<font color=Tomato>**第二部分**</font>-Numpy数组操作  
 
请在下面<font color=Tomato>**每一行注释**</font>下添加对应的代码

<font color=Tomato>7. 修改数组形状</font>  

*reshape(x1,x2)* ， 不改变数据的条件下,将数组的形状改为x1行x2列。  

*数组名.transpose()* ，对换数组的维度，注意该函数不带参数。  

*np.swapaxes(numpy数组名,0,1)* ， 将第1轴与第2轴数据交换。

In [8]:
#7.1 创建包含12个数的一维numpy数组,更改形状为3行4列
a = np.arange(12).reshape(3,4)
print(a)
#再次更改形状为6行2列
a.reshape(6,2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
#7.2 创建包含6个数的一维numpy数组,更改形状为2行3列
b = np.arange(6).reshape(2,3)
print(b)
#将上一步创建好的数组，行列对换
b.T
#将第1轴与第2轴数据交换
print(np.swapaxes(b,0,1))

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


<font color=Tomato>8. 数组链接&分割数组</font>  

*数组名 = np.concatenate((数组1,数组2))* ， 沿指定轴连接相同形状的两个数组；  

*数组名 = np.hstack((数组1,数组2))* ，水平堆叠；  

*数组名 = np.vstack((数组1,数组2))* ， 竖直堆叠。


In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print('a形状：',a)
print('b形状：',b)
#8.1 连接a,b两个数组
c = np.concatenate((a,b))
print(c)
print('c形状：',c)
#8.2 水平堆叠a,b两个数组
c1 = np.hstack((a,b))
print('c1形状：',c1)
#8.3 竖直堆叠a,b两个数组
c2 = np.vstack((a,b))
print('c2形状：',c2)

a形状： [[1 2]
 [3 4]]
b形状： [[11 12]
 [13 14]]
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
c形状： [[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
c1形状： [[ 1  2 11 12]
 [ 3  4 13 14]]
c2形状： [[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]


*np.hsplit(numpy数组,x)* ， 沿x号维度水平分割numpy数组；  

*np.vsplit(numpy数组,x)* ， 沿x号维度垂直分割numpy数组。

In [11]:
c = np.arange(24).reshape(4,6)
print(c)
#8.4 np.hsplit(numpy数组,x) 沿x号维度水平分割numpy数组
np.hsplit(c,2)
#8.5 np.vsplit(numpy数组,x) 沿x号维度垂直分割numpy数组
np.vsplit(c,2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

<font color=Tomato>9. 数组元素添加与删除</font>   

*数组名.resize(a, new_shape)* a：要被resize的数组 ；new_shape：被resize的大小，int或者tuple类型 

<font color=Tomato>注意：</font>  numpy.resize(a, new_shape)和a.resize(new_shape)方法不同

如果new_shape与a相同：二者操作一致，不同处为a.resize为in_place操作

如果new_shape与a不同：二者操作不一致，numpy.resize会取a中的元素进行填充，而a.resize会用0进行填充


In [12]:
d = np.arange(12).reshape(3,4)

#9.1 根据数组d返回4行3列的新数组 
np.resize(d,(4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

*新数组名 = np.append(旧数组名,x)* ,  将x添加到数组末尾

*新数组名 = np.append(旧数组名,x,axis=0)* , 将x添加到数组末尾 维持原有形状  

In [21]:
e = np.arange(6).reshape(2,3)
print(e)
#9.2 将单个元素9添加到数组e末尾
e1 = np.append(e,9)
print(e1)
#9.3 添加数组[1,2]至数组e末尾,维持原有形状
e2 = np.append(e,[1,2,],axis=0)
print(e2)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5 9]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

*np.insert(arr, obj, values, axis)*    

arr原始数组，可一可多，obj插入元素位置，values是插入内容，axis是按行按列插入（0：行、1：列）；  
<font color=Tomato>注意：</font> 如果axis没有给出，相当于是做降维操作，与一维数组一致。

*np.delete(arr,obj,axis=None)*    
arr原始数组 ，obj表明哪一个子向量应该被移除，可以为整数或一个int型的向量， axis表明删除哪个轴的子向量，若默认，则返回一个被拉平的向量。

In [27]:
f = np.array([[1,2,3],[4,5,6]])
#9.4 按行插入数组[7,8,9]至数组f，插入元素位置为1
f1 = np.insert(f,1,[7,8,9],axis=0)
print(f1)
#9.5 删除数组f第三列元素
f2=np.delete(f,2,axis=1)
print(f2)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[1 2]
 [4 5]]


<font color=Tomato>**第三部分**</font>-Numpy数组索引与切片
 
请在下面<font color=Tomato>**每一行注释**</font>下添加对应的代码

*数组名[x]* x为下标   

*数组名[x:y]* x,y为分片区域下标 访问[x,y)上的元素

*数组名[x][y]* 表示矩阵第x行第y列元素

*数组名[x1:x2]* 表示矩阵第x1到x2行的元素 [x1,x2)

*数组名[x1:x2, y1:y2]* 表示矩阵第x1到x2行以及y1到y2列的元素

In [6]:
#10.1 
g = np.array([1,3,5,7,9,11])
#访问数组第一个元素
print(g[0])
#访问数组第一个元素至第四个元素
print(g[0:4])
#10.2 
h = np.array([[13,15,17,19],[12,14,16,18],[11,12,13,15]])
#访问数组第一行第二列元素
print(h[0][1])
#访问数组第二行至第三行元素 
print(h[1:3][:])
#访问数组第二行至第三行 以及 第二列到第三列 的元素 
print(h[1:3,1:4])

1
[1 3 5 7]
15
[[12 14 16 18]
 [11 12 13 15]]
[[14 16 18]
 [12 13 15]]


<font color=Tomato>**第四部分**</font>-Numpy数组运算
 
请在下面<font color=Tomato>**每一行注释**</font>下添加对应的代码

*数组内每个元素扩大x倍,格式为 数组名*x  

*平方 格式为 np.power(数组名,2)*  

*开方 格式为 np.sqrt(数组名)*

*求和 格式为 数组名.sum()*

*求平均 格式为 数组名.mean()*

*求最大数 格式为 数组名.max()*

In [49]:
#10.3 
i = np.array([1,4,9,16])
#数组内每个元素扩大2倍 
print(i*2)
#数组内每个元素平方
i1=np.power(i,2)
print(i1)
#数组内每个元素开方
i2=np.sqrt(i)
print(i2)
#数组求和
i3=i.sum()
print(i3)
#数组求平均
i4=i.mean()
print(i4)
#数组求最大值
i5=i.max()
print(i5)

[ 2  8 18 32]
[  1  16  81 256]
[1. 2. 3. 4.]
30
7.5
16


去重与排序

去重: 新数组 = np.unique(老数组)

排序: 新数组 = np.sort(老数组,x) x为0表示按行，1表示按列

In [53]:
#10.4
h = np.array([1,1,2,2,16])
#数组去重
h1=np.unique(h)
print(h1)
#数组排序
h2=np.sort(h,0)
print(h2)

[ 1  2 16]
[ 1  1  2  2 16]
